# Generated by Django 5.2.3 on 2025-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('kids', 'Kids'), ('podcast', 'Podcast'), ('autres', 'Autres')], max_length=20)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
