# Generated by Django 5.2.3 on 2025-07-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('kids', 'Kids'), ('podcast', 'Podcast'), ('reels', 'Reels'), ('video', 'Video'), ('autres', 'Autres')], max_length=20),
        ),
    ]
