# Generated by Django 5.2.3 on 2025-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0002_video_channel_id_video_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
