# Generated by Django 5.2.3 on 2025-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EldadMedia',
            fields=[
                ('yt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document')], max_length=10)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eldad_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
