# Generated by Django 5.2.3 on 2025-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldadmedia',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
