# Generated by Django 5.2.3 on 2025-07-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_eldadmedia_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldadmedia',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
