# Generated by Django 5.2.3 on 2025-07-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajutorare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldadajutorare',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='eldadajutorare',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ajutorare/'),
        ),
    ]
