# Generated by Django 5.2.3 on 2025-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajutorare', '0002_eldadajutorare_images_eldadajutorare_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eldadajutorare',
            name='images',
        ),
        migrations.AddField(
            model_name='eldadajutorare',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='ajutorare/images/'),
        ),
        migrations.AddField(
            model_name='eldadajutorare',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ajutorare/images/'),
        ),
        migrations.AddField(
            model_name='eldadajutorare',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='ajutorare/images/'),
        ),
        migrations.AddField(
            model_name='eldadajutorare',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='ajutorare/images/'),
        ),
        migrations.AddField(
            model_name='eldadajutorare',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='ajutorare/images/'),
        ),
    ]
