# Generated by Django 5.2.3 on 2025-08-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajutorare', '0003_remove_eldadajutorare_images_eldadajutorare_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eldadajutorare',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proiect/Ajutorare', 'verbose_name_plural': 'Administrare Proiecte/Ajutorare'},
        ),
    ]
